---
- name: Update sources.list
  copy: src=sources.list dest=/etc/apt/sources.list

- name: Update packages
  apt: update_cache=yes cache_valid_time=3600 upgrade=dist

- name: Install core packages
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - vim
    - git-core
    - default-jre
